### ISSUE TITLE
Visualizations based on the submissions

### ISSUE THREAD

**Issue by vigneshjayavel** [dragonslayerx/CodeforcesImporter#26]
For people who rely on codeforces to practice visualizing their submission data would be a great feature to have!
Visualizations can help in
1. motivating the programmer
2. identifying the areas of improvement
3. identifying patterns of time during which he submits successful solutions
4. 1000 more points can be added.. 

> A picture is worth a thousand words..

**Comment by dragonslayerx** [comment]
Exactly what sort of visualisations? can u explain with some example

**Comment by dragonslayerx** [comment]
Thanks :) I will check it out as soon as possible

**Comment by dragonslayerx** [comment]
Thanks It looks great .. Thanks a lot :) :) :+1: ) However its showing some weird G symbols in the X axis. I cant infer their meaning.. Can you fix it. I have attached its pic
![image](https://cloud.githubusercontent.com/assets/6523069/13380839/353f7cd6-de72-11e5-85cd-1611d19e8afa.png)

**Comment by dragonslayerx** [comment]
Seems like changing to this works... Should I change it... 
xAxis: {
    tickInterval: 1,
    labels: {
        enabled: true,
        formatter: function() { return Highcharts.dateFormat('%d %b %y', this.value);},
    }
},

**Comment by vigneshjayavel** [comment]
hey @dragonslayerx awesome! :+1:

**Comment by dragonslayerx** [comment]
:) Merged
