### ISSUE TITLE
errors while running setup.py

### ISSUE THREAD

**Issue by mirkojovanovic** [dragonslayerx/CodeforcesImporter#31]
I get some errors, I tried running it using pyhon2.7, python, python2 and python3. [output](https://ptpb.pw/cMgL) this one is for 2.7

**Comment by dragonslayerx** [comment]
Link is broken. Can you give your codeforces id?

**Comment by dragonslayerx** [comment]
The issue has been resolved. Thanks for reporting. :) You can download the latest version from releases https://github.com/dragonslayerx/CodeforcesImporter/releases
